### PR TITLE
Using the ace editor in the examples

### PR DESCRIPTION
**Pull request by marcusoftnet**
Hi guys, 

I really wanted to understand daSpec but I had a hard time reading the code. Especially the Javascript. 

I added the [Ace](http://ace.c9.io/) editor and highlighted the Javascript with that. 

A few questions:
- Do you think the ace editor is a good idea?
  - If yes then - I mess up the markdown there's a lot of javascript there. Any guidance as to how that works? 
- Is it ok that I reformat the HTML of the example.html... It's a bit messy to work in.
  -- And maybe refactor the javascripts to a separate file?

### CODE REVIEW

**Comment by gojko** [comment]
Hi,

I think the editor is a great idea - I'm away today but we'll merge it in tomorrow, I just don't want to serve anything from an external CDN because that's one more point of failure. 

Regarding cleaning up index - this is on the list of things for this week as well, it's ugly now because it was a hack. it's better to wait until we clean up what we planned and then we can chat about cleaning it up even more

**Comment by marcusoftnet** [comment]
Ok, that's great.

Let's leave this PR here for reference then, so that you can see how I included the ace editor. 
It's probably pretty easy to use if for the markdown / preview stuff too but I got lost in the html/css/javascript codez.

**Comment by gojko** [comment]
we merged ace today into the site - thanks for the idea. I'll close this issue and won't merge the PR as we've done it differently.

**Comment by marcusoftnet** [comment]
Cool! Thanks

**Pull request closed without merging**
